spec-version: 0.30.0
name: preql
version: 0.1
synopsis: experiments with SQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org

library:
  source-dirs: [src]

# Broken, used to test code pre 2019-11
# tests:
#   tests:
#     source-dirs: test
#     main: Test.hs
#     dependencies:
#       - generic-random
#       - QuickCheck
#       - tasty
#       - tasty-hunit
#       - tasty-quickcheck
#       - preql

build-tools:
  - alex
  - happy
      
dependencies:
    - aeson
    - array
    - base
    - binary-parser
    - bytestring
    - bytestring-strict-builder
    - contravariant
    - free
    - mtl
    - postgresql-binary
    - postgresql-libpq
    - postgresql-simple
    - syb
    - template-haskell
    - text
    - th-lift-instances
    - time
    - transformers
    - uuid
    - vector

default-extensions:
  - OverloadedStrings
