spec-version: 0.30.0
name: preql
version: 0.1
synopsis: experiments with SQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org

library:
  source-dirs: [src]

tests:
  tests:
    source-dirs: test
    main: Test.hs
    dependencies:
      - generic-random
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - preql

build-tools:
  - alex
  - happy
      
dependencies:
    - array
    - base
    - binary-parser
    - bytestring
    - contravariant
    - free
    - postgresql-binary
    - postgresql-libpq
    - postgresql-simple
    - syb
    - template-haskell
    - text
    - th-lift-instances
    - transformers
    - vector

default-extensions:
  - OverloadedStrings
