spec-version: 0.30.0
name: preql
version: 0.1
synopsis: safe PostgreSQL queries using Quasiquoters
description: |
  Before you Post(gres)QL, preql.

  Eventually preql quasiquoters will provide syntax checking & optional schema checking.  We're not there yet.
  You may be interested in reading the
  [quickstart](https://github.com/bergey/preql#quickstart) 
  or the [vision](https://github.com/bergey/preql#vision-parsing-sql-in-haskell-quasiquotes)
    
category: Database, PostgreSQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org

library:
  source-dirs: [src]

tests:
  tests:
    source-dirs: test
    main: Test.hs
    dependencies:
      - preql
      - bytestring
      - postgresql-libpq
      - tasty
      - tasty-hunit
      - text
      - uuid
      - vector

build-tools:
  - alex
  - happy
      
dependencies:
    - aeson
    - array
    - base
    - binary-parser
    - bytestring
    - bytestring-strict-builder
    - contravariant
    - free
    - mtl
    - postgresql-binary
    - postgresql-libpq
    - scientific
    - syb
    - template-haskell
    - text
    - th-lift-instances
    - time
    - transformers
    - uuid
    - vector

default-extensions:
  - OverloadedStrings
